# fly.toml app configuration file generated for aurorachat-dev on 2024-01-18T16:42:44-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "aurora-prod"
primary_region = "bos"

[build]

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[checks]
[checks.health]
grace_period = "120s"
interval = "120s"
method = "get"
path = "/"
port = 8080
timeout = "10s"
type = "http"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024
